dist: trusty
sudo: required
services:
- docker

env:
  global:
  - secure: "LI8wGYT9vDMFQTuU+4ZY4mYUpkvm1tIEp57Dx5/1nrasx7CGLV0NTWbIqd+zXWSVeREiWhP9prRdRSahrJxFGWhAmCnyZnnemhGjY18K7TD5YRk/pgK0EZIn465AoBEwo02nObKsEhyVDEhcIHJDrQW3NOKY72yO3FnS7V9rvb0="
  matrix:
  - VARIANT=jessie-amd64
  - VARIANT=jessie-arm64
  - VARIANT=jessie-armel
  - VARIANT=jessie-armhf
  - VARIANT=jessie-i386
  - VARIANT=jessie-kfreebsd-amd64
  - VARIANT=jessie-kfreebsd-i386
  - VARIANT=jessie-mips
  - VARIANT=jessie-mipsel
  - VARIANT=jessie-powerpc
  - VARIANT=jessie-ppc64el
  - VARIANT=jessie-s390x
  - VARIANT=sid-amd64
  - VARIANT=sid-arm64
  - VARIANT=sid-armel
  - VARIANT=sid-armhf
  - VARIANT=sid-hurd-i386
  - VARIANT=sid-i386
  - VARIANT=sid-kfreebsd-amd64
  - VARIANT=sid-kfreebsd-i386
  - VARIANT=sid-mips
  - VARIANT=sid-mips64el
  - VARIANT=sid-mipsel
  - VARIANT=sid-powerpc
  - VARIANT=sid-ppc64el
  - VARIANT=sid-s390x
  - VARIANT=stretch-amd64
  - VARIANT=stretch-arm64
  - VARIANT=stretch-armel
  - VARIANT=stretch-armhf
  - VARIANT=stretch-i386
  - VARIANT=stretch-mips
  - VARIANT=stretch-mips64el
  - VARIANT=stretch-mipsel
  - VARIANT=stretch-ppc64el
  - VARIANT=stretch-s390x
  - VARIANT=wheezy-amd64
  - VARIANT=wheezy-armel
  - VARIANT=wheezy-armhf
  - VARIANT=wheezy-i386
  - VARIANT=wheezy-ia64
  - VARIANT=wheezy-kfreebsd-amd64
  - VARIANT=wheezy-kfreebsd-i386
  - VARIANT=wheezy-mips
  - VARIANT=wheezy-mipsel
  - VARIANT=wheezy-powerpc
  - VARIANT=wheezy-s390
  - VARIANT=wheezy-s390x
  - VARIANT=wheezy-sparc

matrix:
  fast_finish: true
  exclude:
  - env: VARIANT=jessie-kfreebsd-amd64
  - env: VARIANT=jessie-kfreebsd-i386
  - env: VARIANT=sid-hurd-i386
  - env: VARIANT=sid-kfreebsd-amd64
  - env: VARIANT=sid-kfreebsd-i386
  - env: VARIANT=wheezy-ia64
  - env: VARIANT=wheezy-kfreebsd-amd64
  - env: VARIANT=wheezy-kfreebsd-i386
  allow_failures:
  - env: VARIANT=wheezy-ia64
  - env: VARIANT=wheezy-s390
  - env: VARIANT=wheezy-sparc

branches:
  only:
  - master

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ devel main universe'
    packages:
    - binfmt-support
    - debian-archive-keyring
    - debootstrap
    - qemu-user-static

before_install:
- sudo git clone --depth 1 -b mkimage https://github.com/vicamo/docker.git "${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}/docker"
- ln -sf "${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}/docker/contrib/mkimage.sh" ./mkimage.sh
- sudo sed -i -e 's,^DEF_MIRROR=.*$,DEF_MIRROR="http://deb.debian.org/debian",' /usr/sbin/debootstrap

script:
- make V=1 NO_SKIP=1 DOCKER_USER=${DOCKER_USER} -j $(nproc) all-$VARIANT
- docker images | grep ^${DOCKER_USER}/$(cat repo) | awk '{print $1 ":" $2}'

after_success:
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for image in $(docker images | grep ^${DOCKER_USER}/$(cat repo) | awk '{print $1 ":" $2}'); do
      docker push $image;
    done
  fi
